version: '3'

services:
  prisma:
    container_name: jslou-prisma
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
      - '4466:4466'
      - '3001:3001'
    network_mode: host
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: "${MANAGEMENT_API_SECRET}"
        databases:
          default:
            connector: postgres
            host: "${DB_HOST}"
            port: "${DB_PORT}"
            database: "${DB_NAME}"
            user: "${DB_USER}"
            password: "${DB_PASSWORD}"
            rawAccess: true
            migrations: true # Remove after Prod Release
            ssl: true
  api:
    container_name: jslou-api
    build:
      context: ./
      dockerfile: api/Dockerfile
    depends_on:
      - prisma
    ports:
      - '4000:4000'
      - '3001:3001'
    network_mode: host
    environment:
      DEBUG: 1
      NODE_ENV: '${NODE_ENV}'
      REACT_APP_PRISMA_SECRET: '${REACT_APP_PRISMA_SECRET}'
      # For CORS Management
      FRONTEND_URL: '${FRONTEND_URL}'
      BACKEND_URL: '${BACKEND_URL}'
      PLAYGROUND_URL: '${PLAYGROUND_URL}'
      MANAGEMENT_API_SECRET: '${MANAGEMENT_API_SECRET}'
