projects:
  api:
    schemaPath: api/src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: api/src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
# In entrypoint.sh
# hooks:
#   post-deploy:
#     - graphql get-schema -p prisma
